### ISSUE TITLE
Make ESC key not leaving full-screen mode

### ISSUE THREAD

**Issue by sojusnik** [MarkTiedemann/fullscreen#14]
It would be very convenient, if the ESC key wouldn't leave the full-screen mode, when it was summoned with this extension. Only when using the shortcut for this extension a second time, the full-screen mode should be left.

This is needed, because some websites rely on ESC and when using it, you also leave the full-screen mode.

**Comment by th0rgall** [comment]
Hey @sojusnik, thanks for this report! I don't immediately see a way for us to fix this, because the ESC key behavior is [built into](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#Things_your_users_want_to_know) the browser's fullscreen functionality. It's not handled by the extension.

~~A possible workaround would be to detect when the ESC key is pressed, and to automatically restart the fullscreen mode a bit later. This would also not be the best experience of course.~~

Update: We can't even know when the ESC key is pressed, no `keyDown` event is spawned for it while in fullscreen mode, just checked. I don't see a way to fix this, so I'll close the issue.

But if you want this on Chrome or Windows: you can have fullscreen that doesn't exit on ESC without this or any other extension, see [this issue](https://github.com/MarkTiedemann/fullscreen/issues/4#issue-562248086).
