### ISSUE TITLE
Support custom hotkeys

### ISSUE THREAD

**Issue by pat-s** [MarkTiedemann/fullscreen#2]
So that one can e.g. use `command+shift+f` or others instead of the current one.

Thanks for the plugin!

**Comment by MarkTiedemann** [comment]
Yeah, that's a good idea!

Unfortunately, I'm not using this extension anymore. So this is not a priority to me.

@pat-s Do you have time to work on this feature perhaps? Merge Requests are welcome. :)

**Comment by pat-s** [comment]
Uff, no idea about FF extensions unfortunately :) And I'm somewhat OK with the default :)

Is there anything better that you'd recommend? I use it to circumvent the issue of not having a real fullscreen mode in FF on macOS.

**Comment by MarkTiedemann** [comment]
> Uff, no idea about FF extensions unfortunately :)

Well, that's the same problem for me... This is my first FF extension. I don't yet know how to create an options menu.

> Is there anything better that you'd recommend?

Couldn't find anything - that's why I wrote it in the first place, even if it's very basic.

My use case was presenting a website in fullscreen mode. Since I couldn't find an extension that did that for me, I first wrote this code just for that one website presentation (the code running on the website rather than as an extension). After the presentation, I read about how to create a "Hello world" extension, put this code into it, created a FF developer account, published the extension, and that's it - I thought it might be useful for other people as well. :)

In any case, if you need this functionality just for a specific website, I think there are plenty of extensions out there that let you inject JS (for example, [Code Injector](https://addons.mozilla.org/en-US/firefox/addon/codeinjector/)) - you could then copy-and-paste [extension.js](https://github.com/MarkTiedemann/fullscreen/blob/master/extension.js) and change the keys however you like.

I may spend some time on adding a proper options menu to this extension in the future, but I can't promise it. That being said, I'll happily review, merge, and release any merge requests for improving this extension. :)

**Comment by th0rgall** [comment]
@pat-s Independently from this conversation I did that custom hotkey work (& some other stuff). I saw @MarkTiedemann [noticed](https://github.com/th0rgall/fullscreen/issues/1) it has issues, but there's workarounds :) 

If you're using Chrome you can use [this published extension](https://chrome.google.com/webstore/detail/fkbigbddainndbfabdcmbhgionobgina/preview?hl=en-GB).

Firefox is waiting for a small fix and @MarkTiedemann I guess you could update your extension in the store when that's done?

To change the shortcut: navigate to `chrome://extensions/shortcuts`.

The PR is here https://github.com/MarkTiedemann/fullscreen/pull/3

**Comment by pat-s** [comment]
Using FF.

> Firefox is waiting for a small fix and @MarkTiedemann I guess you could update your extension in the store when that's done?

What small fixes do you mean here? Upstream by Mozilla?

**Comment by th0rgall** [comment]
> Using FF.
> 
> > Firefox is waiting for a small fix and @MarkTiedemann I guess you could update your extension in the store when that's done?
> 
> What small fixes do you mean here? Upstream by Mozilla?

Yes, this bug specifically: [https://bugzilla.mozilla.org/show_bug.cgi?id=1612727](https://bugzilla.mozilla.org/show_bug.cgi?id=1612727)

I filed it recently because of this project. But it's not a biggie actually. The extension works in Firefox as the original now (with improvements) with my latest changes: https://github.com/th0rgall/fullscreen

The Firefox link there is still to Mark's old one, you'll have to build & package it for FF yourself now!

**Comment by MarkTiedemann** [comment]
@pat-s With the latest release `0.3.4`, the default shortcut has been changed to `⇧+⌘+I`.

Thanks to @th0rgall, you can now also customize the shortcut and use any combination that you like. To do so,

- go to `about:addons`
- click the settings gear `⚙`
- select `Manage Extension Shortcuts`
- change the shortcut for Fullscreen

Again, many thanks to @th0rgall!

**Comment by pat-s** [comment]
Thanks a lot guys!!

**Comment by MarkTiedemann** [comment]
I think there's one missing todo left from my side: I don't think everyone is aware of the `Manage Extension Shortcuts` menu. So the steps I mentioned above should be documented properly.
